config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    resources :artists

    root to: "users#index"
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :artists

  root to: 'artists#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :artists, only: [:index, :show, :create, :destroy]
      resources :tokens, only: [:create]
    end
    # The following route will match any URL that hasn't been
    # matched already inside the :api namespace.
    # What makes this possible is putting a * in front of
    # the path (i.e. '#unmatched_route').
    # `match` can support multiple HTTP verbs at a time. They
    # must specified with the `via:` argument.
    match '*unmatched_route', to: 'application#not_found', via: :all
  end

end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :user, optional: true

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]

  mount_uploader :image, ImageUploader

  validates(
    :name, {
      presence: { message: 'Name must be provided' },
      uniqueness: { case_sensitive: false }
    }
  )

  before_save :squeeze

  private

  def squeeze
    self.name.squeeze!(' ')
  end

end

app/controllers/admin/artists_controller.rb
module Admin
  class ArtistsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Artist.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Artist.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/artists_controller.rb
class Api::V1::ArtistsController < Api::ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all.order(name: :asc)
    render json: @artists
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    render json: @artist
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    artist = Artist.new(artist_params)

    artist.save!
    render json: { id: artist.id }

  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    if @artist.update(artist_params)
      render json: { message: 'artist updated', id: @artist.id }
    else
      render json: { message: 'artist NOT updated', error: @artist.errors.full_messages }
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    if @artist.destroy
      head :ok
    else
      head :bad_request
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:user_id, :name, :image, :biography, :account_holder, :bank, :branch, :account, :account_type)
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all.order(name: :asc)
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:user_id, :name, :image, :biography, :account_holder, :bank, :branch, :account, :account_type)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :biography %>
    <%= form.text_area :biography, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :account_holder %>
    <%= form.text_field :account_holder, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :bank %>
    <%= form.text_field :bank, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :branch %>
    <%= form.text_field :branch, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :account %>
    <%= form.text_field :account, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :account_type %>
    <%= form.text_field :account_type, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if artist.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', artist, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if artist.persisted? %>
      <%= link_to "Cancel", artist, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", artists_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render 'form', artist: @artist %>

app/views/artists/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Artists</h1>
  </div>

  <div class="col-sm-6 text-right">
    <% if current_user && current_user.admin? %>
      <%= link_to new_artist_path, class: 'btn btn-primary' do %>
        Add New Artist
      <% end %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Biography</th>
      </tr>
    </thead>

    <tbody>
      <% @artists.each do |artist| %>
        <%= content_tag :tr, id: dom_id(artist), class: dom_class(artist) do %>
          <td><%= artist.image ? image_tag(artist.image, height: '64') : '' %></td>
          <td><%= link_to artist.name, artist %></td>
          <td><%= artist.biography %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form', artist: @artist %>

app/views/artists/show.html.erb
<div class="page-header">
  <%= link_to artists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Artists
  <% end %>
  <% if current_user && current_user.admin? %>
    <%= link_to edit_artist_path(@artist), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
    <% end %>
  <% end %>
  <h1>Show artist</h1>
</div>

<dl class="dl-horizontal">
  <% if @artist.image.present? %>
  <div style="float: left; margin: 0 20px 20px 0">
    <%= image_tag @artist.image.url(:medium) %>
  </div>
  <% end %>

  <dt>Name:</dt>
  <dd><%= @artist.name %></dd>

  <dt>Biography:</dt>
  <dd><%= @artist.biography %></dd>

  <hr>

  <dt>Account holder:</dt>
  <dd><%= @artist.account_holder %></dd>

  <dt>Bank:</dt>
  <dd><%= @artist.bank %></dd>

  <dt>Branch:</dt>
  <dd><%= @artist.branch %></dd>

  <dt>Account:</dt>
  <dd><%= @artist.account %></dd>

  <dt>Account type:</dt>
  <dd><%= @artist.account_type %></dd>

</dl>