config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    resources :artists

    root to: "users#index"
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :artists

  root to: 'artists#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :artists, only: [:index, :show, :create, :destroy]
      resources :tokens, only: [:create]
    end
    # The following route will match any URL that hasn't been
    # matched already inside the :api namespace.
    # What makes this possible is putting a * in front of
    # the path (i.e. '#unmatched_route').
    # `match` can support multiple HTTP verbs at a time. They
    # must specified with the `via:` argument.
    match '*unmatched_route', to: 'application#not_found', via: :all
  end

end

app/views/shared/_footer.html.erb
<footer class="footer text-muted bg-light">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <span class="small">© <%= Date.today.year %> <%= Rails.configuration.application_name %></span>
        <ul class="list-inline mb-0 float-right">
          <li class="list-inline-item mr-3 small"><%= link_to "Terms", terms_path %></li>
          <li class="list-inline-item mr-3 small"><%= link_to "Privacy", privacy_path %></li>
        </ul>
      </div>
      <div class="col-12 text-center">
        <span class="small">Developed by <img src="/assets/logo-gustavo-parolin.png" height="24px" alt="Logo Gustavo Parolin"> <a href="http://www.parolin.net/" target="_blank">Gustavo Parolin</a></span>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<% if !current_user.nil? %>
  <% if user_masquerade? %>
    <div class="alert alert-warning text-center">
      You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
      <%= link_to back_masquerade_path(current_user) do %><%= icon("times") %> Logout <% end %>
    </div>
  <% end %>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to notifications_path, class: "nav-link" do %>
            <span><i class="fa fa-flag-o" aria-hidden="true"></i></span>
          <% end %>
         </li>

          <li class="nav-item dropdown">
            <%= link_to root_path, id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag gravatar_image_url(current_user.email, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
              <% if current_user.admin? %>
                <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>